# Generated by Django 5.0.3 on 2024-03-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_category_alter_product_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Техт'),
        ),
        migrations.AddField(
            model_name='product',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Техт'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=32, null=True, verbose_name='Названия'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='Названия'),
        ),
    ]
