# Generated by Django 5.0.3 on 2024-04-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_image_alter_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Названия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Названия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Названия'),
        ),
    ]
