# Generated by Django 5.0.3 on 2024-04-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_title_alter_product_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='box',
            field=models.CharField(choices=[('Мужское', 'Мужское'), ('Женские', 'Женские'), ('Другое', 'Другое')], default='Мужское', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=2),
        ),
    ]
