# Generated by Django 5.0.3 on 2024-04-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_box_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='box',
            field=models.CharField(choices=[('Мужское', 'Мужское'), ('Женские', 'Женские'), ('Другое', 'Другое')], default='Мужское', max_length=16, verbose_name='Выбрать'),
        ),
    ]
